// src/common/constants/error-codes.ts

/**
 * Códigos de error estandarizados para toda la aplicación
 * Formato: DOMINIO_TIPO_DETALLE
 * Ejemplo: USER_VALIDATION_INVALID_EMAIL
 */
export const ErrorCodes = {
  // Errores generales (common)
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_BAD_REQUEST: 'COMMON_BAD_REQUEST',
  COMMON_UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
  COMMON_VALIDATION_ERROR: 'COMMON_VALIDATION_ERROR',
  COMMON_BUSINESS_ERROR: 'COMMON_BUSINESS_ERROR',
  COMMON_DATABASE_ERROR: 'COMMON_DATABASE_ERROR',

  // Errores de usuario
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INVALID_CREDENTIALS: 'USER_INVALID_CREDENTIALS',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_CANNOT_DELETE_SUPER: 'USER_CANNOT_DELETE_SUPER',

  // Errores de proyectos
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_ALREADY_EXISTS: 'PROJECT_ALREADY_EXISTS',
  PROJECT_INVALID_STATE: 'PROJECT_INVALID_STATE',
  PROJECT_HAS_DEPENDENCIES: 'PROJECT_HAS_DEPENDENCIES',

  // Errores de materiales
  MATERIAL_NOT_FOUND: 'MATERIAL_NOT_FOUND',
  MATERIAL_ALREADY_EXISTS: 'MATERIAL_ALREADY_EXISTS',

  // Errores de empleados
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_ALREADY_EXISTS: 'EMPLOYEE_ALREADY_EXISTS',
  EMPLOYEE_HAS_ASSIGNMENTS: 'EMPLOYEE_HAS_ASSIGNMENTS',

  // Errores de base de datos
  DB_FOREIGN_KEY_VIOLATION: 'DB_FOREIGN_KEY_VIOLATION',
  DB_UNIQUE_CONSTRAINT_VIOLATION: 'DB_UNIQUE_CONSTRAINT_VIOLATION',
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_QUERY_ERROR: 'DB_QUERY_ERROR',

  // Errores de autenticación y autorización
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
};

export type ErrorCode = keyof typeof ErrorCodes;
